dist: trusty
sudo: required

language: c
compiler: 
  - gcc

branches:
  only:
    - dev
    
os: 
  - linux
  
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build
